version: '3.9'

services:
  web:
    container_name: local-nginx
    image: nginx
    ports:
      - "8080:80"
  db :
    container_name: local-mysql
    image: library/mysql:8.0.36
    restart: always
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Seoul
    ports:
      - "33060:3306"
    volumes:
      # 디렉토리 마운트 설정
      - ~/programs/docker/mysql8/data:/var/lib/mysql